export { ConsentsDto } from './consents.dto';
export { LogInteractionDto } from './log-interaction.dto';
export { UpdateContactDto } from './update-contact.dto';
export { UpsertContactDto } from './upsert-contact.dto';
export { SegmentFilterDto } from './segment-filter.dto';
export { CreateSegmentDto } from './segment.create.dto';
export { UpdateSegmentDto } from './segment.update.dto';
export { CreateTaskDto } from './task.create.dto';
export { UpdateTaskDto } from './task.update.dto';
export { CrmTaskStatus, CrmTaskPriority } from '../entities/crm-task.entity';
export { CreateCampaignDto } from './campaign.create.dto';
export { UpdateCampaignDto } from './campaign.update.dto';
export { CreateAutomationDto } from './automation.create.dto';
export { UpdateAutomationDto, TriggerAutomationDto } from './automation.update.dto';
export { CreateContactNoteDto } from './contact-note.create.dto';
export { MergeContactsDto } from './merge-contacts.dto';
export { CreatePipelineDto, InitialStageDto } from './pipeline.create.dto';
export { UpdatePipelineDto } from './pipeline.update.dto';
export { CreateStageDto } from './stage.create.dto';
export { UpdateStageDto, StageOrderDto, ReorderStagesDto, MoveContactStageDto } from './stage.update.dto';