import { Injectable, BadRequestException, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In, LessThanOrEqual } from 'typeorm';
import { ReferralCredit } from './entities/referral-credit.entity';
import { WalletUse } from './entities/wallet-use.entity';
import { Booking } from '../bookings/entities/booking.entity';

/**
 * Internal referral wallet.
 *
 * Business rules (normative, see docs/business-rules/payouts-and-referrals.md):
 * - Credits confirm only after the qualifying purchase is COMPLETED and the
 *   72h refund/dispute window has elapsed.
 * - A refund of the qualifying booking voids the reward credit and restores
 *   any wallet credit that was used to pay for it.
 * - Credits expire 12 months after being confirmed.
 */
@Injectable()
export class WalletService {
  private readonly logger = new Logger(WalletService.name);

  constructor(
    @InjectRepository(ReferralCredit)
    private creditRepo: Repository<ReferralCredit>,
    @InjectRepository(WalletUse)
    private useRepo: Repository<WalletUse>,
    @InjectRepository(Booking)
    private bookingRepo: Repository<Booking>,
  ) {}

  private releaseHours(): number {
    const v = Number(process.env.PAYOUT_RELEASE_HOURS ?? 72);
    return Number.isFinite(v) && v >= 0 ? v : 72;
  }

  private ttlMonths(): number {
    const v = Number(process.env.REFERRAL_CREDIT_TTL_MONTHS ?? 12);
    return Number.isFinite(v) && v > 0 ? v : 12;
  }

  async grantPendingCredit(input: {
    referralId: string;
    redemptionId: string;
    userId: string;
    bookingId: string;
    amountCop: number;
    riskStatus: 'clear' | 'pending_review';
  }): Promise<ReferralCredit> {
    const credit = this.creditRepo.create({
      ...input,
      status: 'pending',
    });
    return this.creditRepo.save(credit);
  }

  /**
   * Confirms pending credits whose qualifying booking is completed and past
   * the refund/dispute window. Pending credits on non-completed bookings are
   * voided so a cancelled purchase never leaves a usable reward.
   */
  async confirmEligible(): Promise<number> {
    const now = new Date();
    const pending = await this.creditRepo.find({ where: { status: 'pending' } });
    let confirmed = 0;

    for (const credit of pending) {
      if (credit.riskStatus !== 'clear') continue;

      const booking = await this.bookingRepo.findOne({ where: { id: credit.bookingId } });
      if (!booking) continue;

      if (booking.status !== 'completed' || !booking.completedAt) {
        if (['cancelled', 'refunded'].includes(booking.status)) {
          credit.status = 'voided';
          await this.creditRepo.save(credit);
        }
        continue;
      }

      const disputing = booking.disputedAt && !booking.disputeResolvedAt;
      if (disputing) continue;

      const releaseAfter = new Date(
        new Date(booking.completedAt).getTime() + this.releaseHours() * 3600 * 1000,
      );
      if (releaseAfter.getTime() > now.getTime()) continue;

      credit.status = 'confirmed';
      credit.confirmedAt = now;
      credit.expiresAt = new Date(
        now.getTime() + this.ttlMonths() * 30 * 24 * 3600 * 1000,
      );
      await this.creditRepo.save(credit);
      confirmed += 1;
    }

    if (confirmed) this.logger.log(`Confirmed ${confirmed} referral credit(s)`);
    return confirmed;
  }

  /** Voids reward credits generated by a qualifying booking that got refunded. */
  async voidForQualifyingBooking(bookingId: string): Promise<number> {
    const res = await this.creditRepo.update(
      { bookingId, status: In(['pending', 'confirmed']) },
      { status: 'voided' },
    );
    return res.affected ?? 0;
  }

  /** Restores wallet credit that was used to pay for a refunded booking. */
  async restoreUsedForBooking(bookingId: string): Promise<number> {
    const uses = await this.useRepo.find({ where: { bookingId } });
    if (!uses.length) return 0;

    let restored = 0;
    for (const use of uses) {
      if (!use.creditId) continue;
      const credit = await this.creditRepo.findOne({ where: { id: use.creditId } });
      if (!credit) continue;
      credit.usedCop = Math.max(0, Number(credit.usedCop) - Number(use.amountCop));
      if (credit.status === 'used' && Number(credit.usedCop) < Number(credit.amountCop)) {
        credit.status = 'confirmed';
      }
      await this.creditRepo.save(credit);
      restored += Number(use.amountCop);
    }

    await this.useRepo.delete({ bookingId });
    return restored;
  }

  /** Booking refunded: void any reward credit it generated and restore used credit. */
  async handleBookingRefund(bookingId: string): Promise<void> {
    await this.voidForQualifyingBooking(bookingId);
    await this.restoreUsedForBooking(bookingId);
  }

  async expireCredits(now = new Date()): Promise<number> {
    const res = await this.creditRepo.update(
      { status: 'confirmed', expiresAt: LessThanOrEqual(now) },
      { status: 'expired' },
    );
    return res.affected ?? 0;
  }

  private async usableCredits(userId: string): Promise<ReferralCredit[]> {
    return this.creditRepo.find({
      where: { userId, status: 'confirmed' },
      order: { expiresAt: 'ASC' },
    });
  }

  async getBalance(userId: string): Promise<number> {
    const now = Date.now();
    const credits = await this.usableCredits(userId);
    return Math.round(
      credits.reduce((sum, c) => {
        if (c.expiresAt && c.expiresAt.getTime() <= now) return sum;
        return sum + Math.max(0, Number(c.amountCop) - Number(c.usedCop));
      }, 0) * 100,
    ) / 100;
  }

  async getWallet(userId: string) {
    const credits = await this.creditRepo.find({
      where: { userId },
      order: { createdAt: 'DESC' },
      take: 100,
    });
    return {
      userId,
      currency: 'COP',
      balanceCop: await this.getBalance(userId),
      credits: credits.map((c) => ({
        id: c.id,
        amountCop: Number(c.amountCop),
        usedCop: Number(c.usedCop),
        availableCop: Math.max(0, Number(c.amountCop) - Number(c.usedCop)),
        status: c.status,
        riskStatus: c.riskStatus,
        bookingId: c.bookingId,
        confirmedAt: c.confirmedAt,
        expiresAt: c.expiresAt,
        createdAt: c.createdAt,
      })),
    };
  }

  /**
   * Consumes wallet credit against a booking (earliest-expiring credits first).
   * Throws if the balance is not enough, leaving balances untouched.
   */
  async applyCredit(userId: string, amountCop: number, bookingId: string): Promise<number> {
    if (amountCop <= 0) return 0;

    const now = Date.now();
    const credits = await this.usableCredits(userId);
    let balance = 0;
    for (const c of credits) {
      if (c.expiresAt && c.expiresAt.getTime() <= now) continue;
      balance += Math.max(0, Number(c.amountCop) - Number(c.usedCop));
    }
    if (balance < amountCop) {
      throw new BadRequestException('Insufficient wallet credit');
    }

    let remaining = amountCop;
    let applied = 0;
    for (const credit of credits) {
      if (remaining <= 0) break;
      if (credit.expiresAt && credit.expiresAt.getTime() <= now) continue;
      const available = Number(credit.amountCop) - Number(credit.usedCop);
      if (available <= 0) continue;

      const take = Math.min(remaining, available);
      credit.usedCop = Number(credit.usedCop) + take;
      if (Number(credit.usedCop) >= Number(credit.amountCop)) credit.status = 'used';
      await this.creditRepo.save(credit);
      await this.useRepo.save(
        this.useRepo.create({
          creditId: credit.id,
          userId,
          bookingId,
          amountCop: take,
        }),
      );

      remaining -= take;
      applied += take;
    }

    return applied;
  }

  async clearRiskForRedemption(redemptionId: string): Promise<number> {
    const res = await this.creditRepo.update(
      { redemptionId, status: 'pending' },
      { riskStatus: 'clear' },
    );
    return res.affected ?? 0;
  }

  async voidForRedemption(redemptionId: string): Promise<number> {
    const res = await this.creditRepo.update(
      { redemptionId, status: In(['pending', 'confirmed']) },
      { status: 'voided' },
    );
    return res.affected ?? 0;
  }
}